[constants]
AU = 1.496E+11  # unit of length
GRAV_CONST = 6.67428e-11  # Gravitational constant in SI units
SECONDS_PER_DAY = 86400.0  # unit of time
SOLAR_MASS = 1.98892E+30  # unit of mass

[simulation]
days_per_timestep = 2.0

[colors]
white = [ 255, 255, 255 ]
universe = [ 36, 36, 36 ]
sun = [ 252, 150, 1 ]
mercury = [ 173, 168, 165 ]
venus = [ 227, 158, 28 ]
earth = [ 107, 147, 214 ]
mars = [ 193, 68, 14 ]
jupiter = [ 216, 202, 157 ]
saturn = [ 191, 189, 175 ]
uranus = [ 209, 231, 231 ]
neptune = [ 63, 84, 186 ]

[bodies]  # Metric from: https://nssdc.gsfc.nasa.gov/planetary/factsheet/
sun = { mass = 1.0, radius = 2.0053E-01, distance = 0.0, speed = 0.0 }
mercury = { mass = 1.6592E-07, radius = 3.3422E-02, distance = 0.387, speed = 2.738E-02 }
venus = { mass = 2.4478E-06, radius = 6.0160E-02, distance = 0.723, speed = 2.023E-02 }
earth = { mass = 3.0027E-06, radius = 6.6845E-02, distance = 1.0, speed = 1.720E-02 }
mars = { mass = 3.2128E-07, radius = 3.3422E-02, distance = 1.524, speed = 1.391E-02 }
jupiter = { mass = 0.00095428, radius = 1.3369E-01, distance = 5.204, speed = 7.543E-03 }
saturn = { mass = 0.00028573, radius = 1.2032E-01, distance = 9.573, speed = 5.591E-03 }
uranus = { mass = 4.3646E-05, radius = 9.3583E-02, distance = 19.165, speed = 3.927E-03 }
neptune = { mass = 5.1485E-05, radius = 8.0214E-02, distance = 30.178, speed = 3.136E-03 }
